#application: sprunge-hrd
#version: 2
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest
  #- name: pygments
  #version: latest

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /glipper-sprunge.txt
  static_files: static/glipper-sprunge.txt
  upload: static/glipper-sprunge.txt
- url: /.*
  script: sprunge.app
